"""
Django settings for OJTAPP project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_simple_env_file(path: Path) -> None:
    """
    Minimal .env loader (KEY=VALUE lines). Keeps dependencies at zero.
    Existing environment variables always win.
    """
    try:
        if not path.exists():
            return
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and (key not in os.environ or not os.environ.get(key)):
                os.environ[key] = value
    except Exception:
        # If .env is malformed/unreadable, just fall back to OS env vars.
        return


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


# Load project .env if present
_load_simple_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q!pmbgqsv)ex*oeim(24ndh&*+8+cryv)2-%c=q)+!dns#mfcf'

# SECURITY WARNING: don't run with debug turned on in production!
# On Vercel, default to DEBUG=False even if env var is missing.
IS_VERCEL = str(os.getenv("VERCEL", "")).strip() == "1"
DEBUG = _env_bool("DEBUG", default=(not IS_VERCEL))

# Allow local development from phone/emulator and LAN IP.
# For production, replace with your real domain(s).
ALLOWED_HOSTS = ["*"]

# Auth redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

# OTP registration should be temporary; discard pending data when the browser closes.
SESSION_COOKIE_AGE = 600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CalculateHours.apps.CalculatehoursConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OJTAPP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'DIRS': [BASE_DIR / 'CalculateHours/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OJTAPP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _db_from_supabase_url(db_url: str):
    parsed = urlparse(db_url)
    if parsed.scheme not in ("postgres", "postgresql"):
        raise ValueError("SUPABASE_DATABASE_URL must be a postgres URL")

    # Decode %xx in user/password (required if password has @, :, /, etc.)
    user = unquote(parsed.username or "")
    password = unquote(parsed.password or "")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/") or "postgres",
        "USER": user,
        "PASSWORD": password,
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or 5432),
        # Supabase requires SSL in most environments.
        "OPTIONS": {"sslmode": "require"},
    }


supabase_db_url = os.getenv("SUPABASE_DATABASE_URL", "").strip()

DATABASES = {
    "default": _db_from_supabase_url(supabase_db_url)
    if supabase_db_url
    else {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Where `collectstatic` puts files for production hosts (Vercel).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Project-level static files (e.g. static/js/ojt.js at repo root)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Serve static with WhiteNoise.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Email (SMTP) - Gmail
# Use environment variables so you don't commit credentials to git.
# Set in Windows env:
#   EMAIL_HOST_USER="your-email@gmail.com"
#   EMAIL_HOST_PASSWORD="your-gmail-app-password"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com").strip()
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip().replace(" ", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
